package com.harrypotter.designsystem.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme

internal object CustomColorScheme {
    val dark = darkColorScheme(
        primary = BrandColors.yellow200,
        onPrimary = BrandColors.gray800,
        primaryContainer = BrandColors.yellow600,
        onPrimaryContainer = BrandColors.gray800,
        inversePrimary = BrandColors.gray800,
        secondary = BrandColors.green200,
        onSecondary = BrandColors.gray800,
        secondaryContainer = BrandColors.green800,
        onSecondaryContainer = BrandColors.gray200,
        tertiary = BrandColors.red200,
        onTertiary = BrandColors.gray800,
        tertiaryContainer = BrandColors.red800,
        onTertiaryContainer = BrandColors.gray200,
        background = BrandColors.gray800,
        onBackground = BrandColors.gray200,
        surface = BrandColors.gray800,
        onSurface = BrandColors.gray200,
        surfaceVariant = BrandColors.gray200,
        onSurfaceVariant = BrandColors.gray800,
        surfaceTint = BrandColors.gray800,
        inverseSurface = BrandColors.gray200,
        inverseOnSurface = BrandColors.gray800,
        error = BrandColors.red800,
        onError = BrandColors.gray200,
        errorContainer = BrandColors.red200,
        onErrorContainer = BrandColors.gray200,
        outline = BrandColors.gray200,
        outlineVariant = BrandColors.gray800,
        scrim = BrandColors.gray800,
    )
    val light = lightColorScheme(
        primary = BrandColors.yellow200,
        onPrimary = BrandColors.gray800,
        primaryContainer = BrandColors.yellow600,
        onPrimaryContainer = BrandColors.gray800,
        inversePrimary = BrandColors.gray200,
        secondary = BrandColors.green200,
        onSecondary = BrandColors.gray800,
        secondaryContainer = BrandColors.green800,
        onSecondaryContainer = BrandColors.gray200,
        tertiary = BrandColors.red200,
        onTertiary = BrandColors.gray800,
        tertiaryContainer = BrandColors.red800,
        onTertiaryContainer = BrandColors.gray200,
        background = BrandColors.gray200,
        onBackground = BrandColors.gray800,
        surface = BrandColors.gray200,
        onSurface = BrandColors.gray800,
        surfaceVariant = BrandColors.gray800,
        onSurfaceVariant = BrandColors.gray200,
        surfaceTint = BrandColors.gray200,
        inverseSurface = BrandColors.gray800,
        inverseOnSurface = BrandColors.gray200,
        error = BrandColors.red800,
        onError = BrandColors.gray200,
        errorContainer = BrandColors.red200,
        onErrorContainer = BrandColors.gray200,
        outline = BrandColors.gray800,
        outlineVariant = BrandColors.gray200,
        scrim = BrandColors.gray800,
    )
}