package com.harrypotter.designsystem.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme

object CustomStyle {
    val dark = darkColorScheme(
        primary = CustomColors.yellow200,
        onPrimary = CustomColors.gray800,
        primaryContainer = CustomColors.yellow600,
        onPrimaryContainer = CustomColors.gray800,
        inversePrimary = CustomColors.gray800,
        secondary = CustomColors.green200,
        onSecondary = CustomColors.gray800,
        secondaryContainer = CustomColors.green800,
        onSecondaryContainer = CustomColors.gray200,
        tertiary = CustomColors.red200,
        onTertiary = CustomColors.gray800,
        tertiaryContainer = CustomColors.red800,
        onTertiaryContainer = CustomColors.gray200,
        background = CustomColors.gray800,
        onBackground = CustomColors.gray200,
        surface = CustomColors.gray800,
        onSurface = CustomColors.gray200,
        surfaceVariant = CustomColors.gray200,
        onSurfaceVariant = CustomColors.gray800,
        surfaceTint = CustomColors.gray800,
        inverseSurface = CustomColors.gray200,
        inverseOnSurface = CustomColors.gray800,
        error = CustomColors.red800,
        onError = CustomColors.gray200,
        errorContainer = CustomColors.red200,
        onErrorContainer = CustomColors.gray200,
        outline = CustomColors.gray200,
        outlineVariant = CustomColors.gray800,
        scrim = CustomColors.gray800,
    )
    val light = lightColorScheme(
        primary = CustomColors.yellow200,
        onPrimary = CustomColors.gray800,
        primaryContainer = CustomColors.yellow600,
        onPrimaryContainer = CustomColors.gray800,
        inversePrimary = CustomColors.gray200,
        secondary = CustomColors.green200,
        onSecondary = CustomColors.gray800,
        secondaryContainer = CustomColors.green800,
        onSecondaryContainer = CustomColors.gray200,
        tertiary = CustomColors.red200,
        onTertiary = CustomColors.gray800,
        tertiaryContainer = CustomColors.red800,
        onTertiaryContainer = CustomColors.gray200,
        background = CustomColors.gray200,
        onBackground = CustomColors.gray800,
        surface = CustomColors.gray200,
        onSurface = CustomColors.gray800,
        surfaceVariant = CustomColors.gray800,
        onSurfaceVariant = CustomColors.gray200,
        surfaceTint = CustomColors.gray200,
        inverseSurface = CustomColors.gray800,
        inverseOnSurface = CustomColors.gray200,
        error = CustomColors.red800,
        onError = CustomColors.gray200,
        errorContainer = CustomColors.red200,
        onErrorContainer = CustomColors.gray200,
        outline = CustomColors.gray800,
        outlineVariant = CustomColors.gray200,
        scrim = CustomColors.gray800,
    )
}